# Scan the Dockerfile for issues & CVEs
name: Dockerfile check Lint

on:
  workflow_call:
  # push:
  #   branches: [ work-space ]



jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Validate Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile