# uses Trivy to scan the docker image for vulnerabilities. The image is built and pushed to Docker Hub in the build-and-push.yml workflow.
name: docker Image Scanner

on: 
  workflow_call:

jobs:
    image-scanner:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Trivy Scanner
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: ${{ vars.DOCKERHUB_USER }}/tws_shop:latest #${{ github.sha }} # I will use for test tag latest but in production I will use the commit sha as tag to scan the exact image that was built and pushed in the build-and-push.yml workflow.
                severity: 'CRITICAL,HIGH'
                exit-code: '0'
                trivyignore: ${{ github.workspace }}/.trivyignore